const uid=()=>window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const todayIso=()=>{const d=new Date();return localIso(d)};
const localIso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseDate=s=>new Date(s+'T12:00:00');
const fmtDate=s=>s?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(parseDate(s)):'–';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const store={get:(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const defaultRooms=[
{id:'r1',name:'Seminarraum Luther',type:'Seminarraum',capacity:30,note:'Beamer · WLAN',cleaning:'done'},
{id:'r2',name:'Seminarraum Melanchthon',type:'Seminarraum',capacity:18,note:'Flipchart · WLAN',cleaning:'done'},
{id:'r3',name:'Besprechungsraum 1',type:'Besprechungsraum',capacity:8,note:'Bildschirm',cleaning:'done'},
{id:'r4',name:'Gästezimmer 201',type:'Einzelzimmer',capacity:1,note:'1 Einzelbett',cleaning:'done'},
{id:'r5',name:'Gästezimmer 202',type:'Doppelzimmer',capacity:2,note:'Doppelbett',cleaning:'open'},
{id:'r6',name:'Gästezimmer 203',type:'Einzelzimmer',capacity:1,note:'1 Einzelbett',cleaning:'done'},
{id:'r7',name:'Gästezimmer 204',type:'Doppelzimmer',capacity:2,note:'2 Einzelbetten',cleaning:'done'},
{id:'r8',name:'Gruppenraum',type:'Veranstaltungsraum',capacity:24,note:'Flexible Bestuhlung',cleaning:'done'}];
let rooms=store.get('raumwerk_rooms_v2',null)||defaultRooms;
let bookings=store.get('raumwerk_bookings',[]).map(b=>({...b,roomId:String(b.roomId).startsWith('r')?String(b.roomId):'r'+b.roomId,status:b.status||'confirmed'}));
let guests=store.get('raumwerk_guests',[]);
let tasks=store.get('raumwerk_tasks',[]);
let settings=store.get('raumwerk_settings',{org:'Evangelische Einrichtung',email:'',phone:'',address:''});
let currentMonth=new Date();currentMonth.setDate(1);let taskFilter='open';
const pageMeta={dashboard:['Dashboard','Alles Wichtige auf einen Blick'],calendar:['Buchungskalender','Belegung sehen, buchen, ändern oder stornieren'],rooms:['Räume & Zimmer','Bestand und Kapazitäten einfach verwalten'],guests:['Gäste & Kunden','Kontakte und Buchungshistorie zentral'],cleaning:['Reinigung','Sofort sehen, was offen oder erledigt ist'],tasks:['Aufgaben','Kleine To-dos ohne Zettelwirtschaft'],documents:['Dokumente','Bestätigungen und Exporte aus vorhandenen Daten'],settings:['Einstellungen','Einrichtung und Datenverwaltung']};
function persist(){store.set('raumwerk_rooms_v2',rooms);store.set('raumwerk_bookings',bookings);store.set('raumwerk_guests',guests);store.set('raumwerk_tasks',tasks);store.set('raumwerk_settings',settings)}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function closeModal(id){document.getElementById(id).classList.remove('show')}
function showModal(id){document.getElementById(id).classList.add('show')}
function showFormError(id,msg){const e=document.getElementById(id);e.textContent=msg;e.style.display='block'}
function hideFormError(id){document.getElementById(id).style.display='none'}
function toggleMenu(){document.getElementById('sidebar').classList.toggle('mobile-open')}
function goPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-'+page).classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.getElementById('pageTitle').textContent=pageMeta[page][0];document.getElementById('pageSubtitle').textContent=pageMeta[page][1];document.getElementById('sidebar').classList.remove('mobile-open');renderPage(page);window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>goPage(b.dataset.page)));
function overlaps(aFrom,aTo,bFrom,bTo){return aFrom<=bTo&&aTo>=bFrom}
function bookingConflict(roomId,from,to,ignoreId=''){return bookings.some(b=>b.id!==ignoreId&&b.status!=='cancelled'&&b.roomId===roomId&&overlaps(from,to,b.from,b.to))}
function bookedOn(roomId,date){return bookings.some(b=>b.status!=='cancelled'&&b.roomId===roomId&&b.from<=date&&b.to>=date)}
function bookingState(b){const t=todayIso();if(b.status==='cancelled')return ['Storniert','red'];if(b.status==='option')return ['Option','yellow'];if(b.to<t)return ['Abgeschlossen','green'];if(b.from>t)return ['Kommend','blue'];return ['Aktiv','orange']}
function roomName(id){return rooms.find(r=>r.id===id)?.name||'Unbekannter Raum'}
function renderAll(){persist();renderDashboard();renderCalendar();renderBookingTable();renderRoomsPage();renderGuestsPage();renderCleaning();renderTasks();fillSelectors();renderSettings()}
function renderPage(page){if(page==='dashboard')renderDashboard();if(page==='calendar'){renderCalendar();renderBookingTable()}if(page==='rooms')renderRoomsPage();if(page==='guests')renderGuestsPage();if(page==='cleaning')renderCleaning();if(page==='tasks')renderTasks();if(page==='documents')fillDocumentPicker();if(page==='settings')renderSettings()}
function renderDashboard(){const t=todayIso();const occupied=rooms.filter(r=>bookedOn(r.id,t)).length;const arrivals=bookings.filter(b=>b.status!=='cancelled'&&b.from===t).length;const openTasks=tasks.filter(x=>!x.done).length+rooms.filter(r=>r.cleaning!=='done').length;document.getElementById('statRooms').textContent=rooms.length;document.getElementById('statOccupied').textContent=occupied;document.getElementById('statOccupiedSub').textContent=`von ${rooms.length} Räumen`;document.getElementById('statArrivals').textContent=arrivals;document.getElementById('statTasks').textContent=openTasks;
const upcoming=[...bookings].filter(b=>b.status!=='cancelled'&&b.to>=t).sort((a,b)=>a.from.localeCompare(b.from)).slice(0,6);document.getElementById('dashboardBookings').innerHTML=upcoming.length?upcoming.map(b=>`<div class="row"><div class="row-main"><div class="row-title">${esc(b.guest)}</div><div class="row-meta">${esc(roomName(b.roomId))} · ${fmtDate(b.from)} – ${fmtDate(b.to)}${b.purpose?' · '+esc(b.purpose):''}</div></div><span class="badge ${bookingState(b)[1]}">${bookingState(b)[0]}</span></div>`).join(''):'<div class="empty">Keine kommenden Buchungen. Über „Neue Buchung“ geht es sofort los.</div>';
const clean=rooms.filter(r=>r.cleaning!=='done').slice(0,5);document.getElementById('dashboardCleaning').innerHTML=clean.length?clean.map(r=>`<div class="row"><div><div class="row-title">${esc(r.name)}</div><div class="row-meta">${esc(r.type)}</div></div><span class="badge ${r.cleaning==='doing'?'yellow':'red'}">${r.cleaning==='doing'?'In Reinigung':'Offen'}</span></div>`).join(''):'<div class="empty">Alles sauber ✓</div>';
const open=tasks.filter(x=>!x.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,5);document.getElementById('dashboardTasks').innerHTML=open.length?open.map(tk=>`<div class="row"><div><div class="row-title">${esc(tk.title)}</div><div class="row-meta">${tk.due?'Fällig '+fmtDate(tk.due):'Ohne Termin'}${tk.owner?' · '+esc(tk.owner):''}</div></div><span class="badge blue">Offen</span></div>`).join(''):'<div class="empty">Keine offenen Aufgaben ✓</div>'}
function renderCalendar(){const grid=document.getElementById('calendarGrid');if(!grid)return;const y=currentMonth.getFullYear(),m=currentMonth.getMonth();document.getElementById('calendarLabel').textContent=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(currentMonth);const weekdays=['Mo','Di','Mi','Do','Fr','Sa','So'];let html=weekdays.map(w=>`<div class="weekday">${w}</div>`).join('');const first=new Date(y,m,1);const offset=(first.getDay()+6)%7;const start=new Date(y,m,1-offset);for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=localIso(d),other=d.getMonth()!==m,isToday=iso===todayIso();const ev=bookings.filter(b=>b.status!=='cancelled'&&b.from<=iso&&b.to>=iso).slice(0,3);const count=bookings.filter(b=>b.status!=='cancelled'&&b.from<=iso&&b.to>=iso).length;html+=`<div class="day ${other?'other':''} ${isToday?'today':''}" ondblclick="openBookingModal(null,'${iso}')"><div class="day-num">${d.getDate()}</div>${ev.map(b=>`<div class="cal-event" title="${esc(b.guest)} – ${esc(roomName(b.roomId))}" onclick="editBooking('${b.id}');event.stopPropagation()">${esc(roomName(b.roomId))} · ${esc(b.guest)}</div>`).join('')}${count>3?`<div class="cal-more">+ ${count-3} weitere</div>`:''}</div>`}grid.innerHTML=html}
function changeMonth(delta){currentMonth.setMonth(currentMonth.getMonth()+delta);renderCalendar()}
function scrollToBookingList(){document.getElementById('bookingListPanel').scrollIntoView({behavior:'smooth'})}
function renderBookingTable(){const body=document.getElementById('bookingTable');if(!body)return;const q=(document.getElementById('bookingSearch')?.value||'').toLowerCase();const list=[...bookings].filter(b=>[b.guest,roomName(b.roomId),b.purpose,b.from,b.to].join(' ').toLowerCase().includes(q)).sort((a,b)=>b.from.localeCompare(a.from));body.innerHTML=list.length?list.map(b=>{const st=bookingState(b);return `<tr><td>${fmtDate(b.from)} – ${fmtDate(b.to)}</td><td><strong>${esc(b.guest)}</strong></td><td>${esc(roomName(b.roomId))}</td><td>${esc(b.purpose||'–')}</td><td><span class="badge ${st[1]}">${st[0]}</span></td><td><div class="row-actions"><button class="btn small" onclick="editBooking('${b.id}')">Bearbeiten</button><button class="btn small danger" onclick="deleteBooking('${b.id}')">Löschen</button></div></td></tr>`}).join(''):'<tr><td colspan="6"><div class="empty">Keine Buchungen gefunden.</div></td></tr>'}
function fillSelectors(){const opts=rooms.map(r=>`<option value="${r.id}">${esc(r.name)} · ${esc(r.type)}</option>`).join('');document.getElementById('bookingRoom').innerHTML=opts;document.getElementById('taskRoom').innerHTML='<option value="">Kein Raum</option>'+opts;document.getElementById('guestNames').innerHTML=guests.map(g=>`<option value="${esc(g.name)}"></option>`).join('');fillDocumentPicker()}
function openBookingModal(id=null,date=null){hideFormError('bookingError');document.getElementById('bookingId').value='';document.getElementById('bookingModalTitle').textContent='Neue Buchung';document.getElementById('bookingGuest').value='';document.getElementById('bookingPurpose').value='';document.getElementById('bookingParticipants').value='';document.getElementById('bookingNote').value='';document.getElementById('bookingStatus').value='confirmed';document.getElementById('bookingFrom').value=date||todayIso();document.getElementById('bookingTo').value=date||todayIso();fillSelectors();if(id)editBooking(id,true);else showModal('bookingModal')}
function editBooking(id,alreadyOpen=false){const b=bookings.find(x=>x.id===id);if(!b)return;hideFormError('bookingError');document.getElementById('bookingId').value=b.id;document.getElementById('bookingModalTitle').textContent='Buchung bearbeiten';document.getElementById('bookingGuest').value=b.guest;document.getElementById('bookingRoom').value=b.roomId;document.getElementById('bookingFrom').value=b.from;document.getElementById('bookingTo').value=b.to;document.getElementById('bookingPurpose').value=b.purpose||'';document.getElementById('bookingParticipants').value=b.participants||'';document.getElementById('bookingStatus').value=b.status||'confirmed';document.getElementById('bookingNote').value=b.note||'';if(!alreadyOpen)showModal('bookingModal')}
function saveBooking(){hideFormError('bookingError');const id=document.getElementById('bookingId').value;const roomId=document.getElementById('bookingRoom').value;const guest=document.getElementById('bookingGuest').value.trim();const from=document.getElementById('bookingFrom').value,to=document.getElementById('bookingTo').value;const status=document.getElementById('bookingStatus').value;if(!guest||!roomId||!from||!to)return showFormError('bookingError','Bitte Gast/Kunde, Raum und Zeitraum vollständig angeben.');if(to<from)return showFormError('bookingError','Das Bis-Datum darf nicht vor dem Von-Datum liegen.');if(status!=='cancelled'&&bookingConflict(roomId,from,to,id))return showFormError('bookingError',`${roomName(roomId)} ist in diesem Zeitraum bereits belegt.`);const data={id:id||uid(),roomId,guest,from,to,purpose:document.getElementById('bookingPurpose').value.trim(),participants:Number(document.getElementById('bookingParticipants').value)||null,status,note:document.getElementById('bookingNote').value.trim(),createdAt:id?(bookings.find(b=>b.id===id)?.createdAt||new Date().toISOString()):new Date().toISOString()};if(id)bookings=bookings.map(b=>b.id===id?data:b);else bookings.push(data);ensureGuestFromBooking(guest);persist();closeModal('bookingModal');renderAll();toast(id?'Buchung geändert':'Buchung gespeichert')}
function deleteBooking(id){const b=bookings.find(x=>x.id===id);if(!b||!confirm(`Buchung von ${b.guest} wirklich löschen?`))return;bookings=bookings.filter(x=>x.id!==id);persist();renderAll();toast('Buchung gelöscht')}
function ensureGuestFromBooking(name){if(!guests.some(g=>g.name.toLowerCase()===name.toLowerCase()))guests.push({id:uid(),name,email:'',phone:'',note:''})}