const uid=()=>window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const todayIso=()=>{const d=new Date();return localIso(d)};
const localIso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseDate=s=>new Date(s+'T12:00:00');
const fmtDate=s=>s?new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(parseDate(s)):'–';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const store={get:(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const defaultRooms=[
{id:'r1',name:'Seminarraum Luther',type:'Seminarraum',capacity:30,note:'Beamer · WLAN',cleaning:'done'},
{id:'r2',name:'Seminarraum Melanchthon',type:'Seminarraum',capacity:18,note:'Flipchart · WLAN',cleaning:'done'},
{id:'r3',name:'Besprechungsraum 1',type:'Besprechungsraum',capacity:8,note:'Bildschirm',cleaning:'done'},
{id:'r4',name:'Gästezimmer 201',type:'Einzelzimmer',capacity:1,note:'1 Einzelbett',cleaning:'done'},
{id:'r5',name:'Gästezimmer 202',type:'Doppelzimmer',capacity:2,note:'Doppelbett',cleaning:'open'},
{id:'r6',name:'Gästezimmer 203',type:'Einzelzimmer',capacity:1,note:'1 Einzelbett',cleaning:'done'},
{id:'r7',name:'Gästezimmer 204',type:'Doppelzimmer',capacity:2,note:'2 Einzelbetten',cleaning:'done'},
{id:'r8',name:'Gruppenraum',type:'Veranstaltungsraum',capacity:24,note:'Flexible Bestuhlung',cleaning:'done'}];
let rooms=store.get('raumwerk_rooms_v2',null)||defaultRooms;
let bookings=store.get('raumwerk_bookings',[]).map(b=>({...b,roomId:String(b.roomId).startsWith('r')?String(b.roomId):'r'+b.roomId,status:b.status||'confirmed'}));
let guests=store.get('raumwerk_guests',[]);
let tasks=store.get('raumwerk_tasks',[]);
let settings=store.get('raumwerk_settings',{org:'Evangelische Einrichtung',email:'',phone:'',address:''});
let currentMonth=new Date();currentMonth.setDate(1);let taskFilter='open';
const pageMeta={dashboard:['Dashboard','Alles Wichtige auf einen Blick'],calendar:['Buchungskalender','Belegung sehen, buchen, ändern oder stornieren'],rooms:['Räume & Zimmer','Bestand und Kapazitäten einfach verwalten'],guests:['Gäste & Kunden','Kontakte und Buchungshistorie zentral'],cleaning:['Reinigung','Sofort sehen, was offen oder erledigt ist'],tasks:['Aufgaben','Kleine To-dos ohne Zettelwirtschaft'],documents:['Dokumente','Bestätigungen und Exporte aus vorhandenen Daten'],settings:['Einstellungen','Einrichtung und Datenverwaltung']};

const cloud={mode:'checking',version:0,user:null,organization:null,suspend:false,saveTimer:null};
window.raumwerkCloud=cloud;
const roleLabel={admin:'Administrator',manager:'Leitung',staff:'Mitarbeiter',cleaning:'Reinigung',viewer:'Nur lesen'};
function stateSnapshot(){return {rooms:JSON.parse(JSON.stringify(rooms)),bookings:JSON.parse(JSON.stringify(bookings)),guests:JSON.parse(JSON.stringify(guests)),tasks:JSON.parse(JSON.stringify(tasks)),settings:JSON.parse(JSON.stringify(settings))}}
function persistLocal(){store.set('raumwerk_rooms_v2',rooms);store.set('raumwerk_bookings',bookings);store.set('raumwerk_guests',guests);store.set('raumwerk_tasks',tasks);store.set('raumwerk_settings',settings)}
function persist(){persistLocal();if(cloud.mode==='online'&&!cloud.suspend)scheduleCloudSave()}
function scheduleCloudSave(){clearTimeout(cloud.saveTimer);cloud.saveTimer=setTimeout(saveCloudState,250)}
async function saveCloudState(){if(cloud.mode!=='online')return;const snapshot=stateSnapshot();try{const res=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:cloud.version,state:snapshot})});const data=await res.json();if(res.ok){cloud.version=data.version;setSyncBadge('Gespeichert','ok');return}if(res.status===409&&data.code==='VERSION_CONFLICT'){store.set('raumwerk_conflict_backup',snapshot);setSyncBadge('Neu laden','warn');alert('Ein anderer Benutzer hat die Daten inzwischen geändert. Dein letzter lokaler Stand wurde als Konflikt-Sicherung gespeichert; der aktuelle gemeinsame Stand wird jetzt neu geladen.');await loadCloudState();return}if(res.status===403){setSyncBadge('Keine Rechte','warn');alert(data.error||'Für diese Änderung fehlen die Rechte. Der gemeinsame Stand wird wiederhergestellt.');await loadCloudState();return}throw new Error(data.error||'Speichern fehlgeschlagen')}catch(e){console.error(e);setSyncBadge('Nicht synchronisiert','warn');}}
function setSyncBadge(text,state=''){let el=document.getElementById('cloudSyncBadge');if(!el)return;el.textContent=text;el.dataset.state=state}
async function cloudBoot(){injectCloudUi();try{const statusRes=await fetch('/api/bootstrap/status',{headers:{Accept:'application/json'}});if(!statusRes.ok)throw new Error('API nicht aktiv');const status=await statusRes.json();if(status.needsSetup){showCloudSetup();return}const me=await fetch('/api/me',{headers:{Accept:'application/json'}});if(me.status===401){showCloudLogin();return}if(!me.ok)throw new Error('Anmeldung konnte nicht geprüft werden');const data=await me.json();cloud.user=data.user;cloud.organization=data.organization;await loadCloudState();}catch(e){cloud.mode='local';hideCloudGate();setLocalBadge();}}
async function loadCloudState(){const res=await fetch('/api/state',{headers:{Accept:'application/json'}});if(res.status===401){cloud.mode='checking';showCloudLogin();return}const data=await res.json();if(!res.ok)throw new Error(data.error||'Daten konnten nicht geladen werden');cloud.suspend=true;rooms=Array.isArray(data.state.rooms)?data.state.rooms:[];bookings=Array.isArray(data.state.bookings)?data.state.bookings:[];guests=Array.isArray(data.state.guests)?data.state.guests:[];tasks=Array.isArray(data.state.tasks)?data.state.tasks:[];settings=data.state.settings||settings;cloud.version=data.version;cloud.user=data.user||cloud.user;cloud.mode='online';persistLocal();renderAll();cloud.suspend=false;hideCloudGate();decorateCloudUser();applyRoleUi();setSyncBadge('Gespeichert','ok');}
function injectCloudUi(){if(document.getElementById('cloudGate'))return;const style=document.createElement('style');style.textContent=`
#cloudGate{position:fixed;inset:0;z-index:99999;background:#f5f7fb;display:flex;align-items:center;justify-content:center;padding:20px}#cloudGate.hidden{display:none}.cloud-box{width:min(440px,100%);background:#fff;border:1px solid #e3e8f0;border-radius:18px;padding:28px;box-shadow:0 24px 70px #17203320}.cloud-logo{font-size:23px;font-weight:900;letter-spacing:.4px}.cloud-logo span{display:block;font-size:12px;color:#7c8799;font-weight:600;margin-top:4px}.cloud-box h2{margin:25px 0 5px}.cloud-box p{color:#748095;font-size:14px}.cloud-field{margin:13px 0}.cloud-field label{display:block;font-size:12px;font-weight:800;margin-bottom:6px}.cloud-field input,.cloud-field select{width:100%;padding:12px;border:1px solid #dbe1ea;border-radius:10px;font:inherit}.cloud-submit{width:100%;margin-top:10px;padding:12px;border:0;border-radius:10px;background:#335cff;color:#fff;font-weight:800;cursor:pointer}.cloud-error{display:none;background:#fff0f0;color:#a52b2b;padding:10px;border-radius:9px;font-size:13px;margin:12px 0}.cloud-account{display:flex;align-items:center;gap:9px;padding:7px 11px;border:1px solid #e1e6ee;border-radius:10px;background:#fff;font-size:12px}.cloud-account b{display:block}.cloud-account button{border:0;background:transparent;cursor:pointer;color:#5c6680}.cloud-sync[data-state=ok]{color:#16794a}.cloud-sync[data-state=warn]{color:#a15c14}.cloud-users{margin-top:15px}.cloud-user-row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-top:1px solid #edf0f4;font-size:13px}html[data-role="cleaning"] #nav button:not([data-page="dashboard"]):not([data-page="cleaning"]),html[data-role="cleaning"] .top-actions{display:none!important}html[data-role="viewer"] .btn.primary,html[data-role="viewer"] .btn.danger,html[data-role="viewer"] .row-actions,html[data-role="viewer"] .room-actions{display:none!important}html[data-role="staff"] #page-rooms .toolbar .primary,html[data-role="staff"] #page-rooms .room-actions button:nth-child(n+2),html[data-role="staff"] #page-settings .panel:first-child button{display:none!important}
`;document.head.appendChild(style);document.body.insertAdjacentHTML('beforeend',`<div id="cloudGate"><div class="cloud-box" id="cloudGateBox"><div class="cloud-logo">RAUMWERK<span>Zentrale Raum- & Zimmerverwaltung</span></div><h2>Verbindung wird geprüft …</h2><p>Einen Moment, die gemeinsame Datenbasis wird geladen.</p></div></div>`)}
function hideCloudGate(){document.getElementById('cloudGate')?.classList.add('hidden')}
function showCloudLogin(){const gate=document.getElementById('cloudGate');gate.classList.remove('hidden');document.getElementById('cloudGateBox').innerHTML=`<div class="cloud-logo">RAUMWERK<span>Raum- & Zimmerverwaltung</span></div><h2>Anmelden</h2><p>Einloggen und direkt mit dem gemeinsamen Stand weiterarbeiten.</p><div class="cloud-error" id="cloudAuthError"></div><form onsubmit="cloudLogin(event)"><div class="cloud-field"><label>E-Mail</label><input id="cloudEmail" type="email" autocomplete="username" required></div><div class="cloud-field"><label>Passwort</label><input id="cloudPassword" type="password" autocomplete="current-password" required></div><button class="cloud-submit">Anmelden</button></form>`}
function showCloudSetup(){const gate=document.getElementById('cloudGate');gate.classList.remove('hidden');document.getElementById('cloudGateBox').innerHTML=`<div class="cloud-logo">RAUMWERK<span>Ersteinrichtung</span></div><h2>In 30 Sekunden startklar</h2><p>Dieser erste Zugang wird Administrator. Bereits vorhandene lokale Räume und Buchungen werden übernommen.</p><div class="cloud-error" id="cloudAuthError"></div><form onsubmit="cloudSetup(event)"><div class="cloud-field"><label>Einrichtung</label><input id="cloudOrg" value="${esc(settings.org||'')}" required></div><div class="cloud-field"><label>Dein Name</label><input id="cloudName" required></div><div class="cloud-field"><label>E-Mail</label><input id="cloudEmail" type="email" autocomplete="username" required></div><div class="cloud-field"><label>Passwort (mind. 10 Zeichen)</label><input id="cloudPassword" type="password" minlength="10" autocomplete="new-password" required></div><button class="cloud-submit">RAUMWERK einrichten</button></form>`}
function cloudAuthError(msg){const e=document.getElementById('cloudAuthError');if(e){e.textContent=msg;e.style.display='block'}}
async function cloudLogin(e){e.preventDefault();cloudAuthError('');const res=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('cloudEmail').value,password:document.getElementById('cloudPassword').value})});const data=await res.json();if(!res.ok)return cloudAuthError(data.error||'Anmeldung fehlgeschlagen.');cloud.user=data.user;cloud.organization=data.organization;await loadCloudState()}
async function cloudSetup(e){e.preventDefault();cloudAuthError('');const body={organization:document.getElementById('cloudOrg').value,name:document.getElementById('cloudName').value,email:document.getElementById('cloudEmail').value,password:document.getElementById('cloudPassword').value,state:stateSnapshot()};const res=await fetch('/api/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)return cloudAuthError(data.error||'Einrichtung fehlgeschlagen.');cloud.user=data.user;cloud.organization=data.organization;await loadCloudState()}
async function cloudLogout(){await fetch('/api/logout',{method:'POST'});cloud.mode='checking';cloud.user=null;document.getElementById('cloudAccount')?.remove();showCloudLogin()}
function setLocalBadge(){const top=document.querySelector('.top-actions');if(top&&!document.getElementById('cloudLocalBadge'))top.insertAdjacentHTML('afterbegin','<span class="cloud-account" id="cloudLocalBadge"><b>Lokaler Modus</b></span>')}
function decorateCloudUser(){document.getElementById('cloudLocalBadge')?.remove();let top=document.querySelector('.top-actions');if(!top||!cloud.user)return;document.getElementById('cloudAccount')?.remove();top.insertAdjacentHTML('afterbegin',`<div class="cloud-account" id="cloudAccount"><div><b>${esc(cloud.user.name)}</b><span>${esc(roleLabel[cloud.user.role]||cloud.user.role)} · <span class="cloud-sync" id="cloudSyncBadge">Gespeichert</span></span></div><button onclick="cloudLogout()" title="Abmelden">Abmelden</button></div>`);renderCloudAccountPanel()}
function applyRoleUi(){document.documentElement.dataset.role=cloud.user?.role||'';if(cloud.user?.role==='cleaning')goPage('cleaning')}
function renderCloudAccountPanel(){const grid=document.querySelector('#page-settings .settings-grid');if(!grid||document.getElementById('cloudUsersPanel')||!cloud.user)return;const canManage=['admin','manager'].includes(cloud.user.role);grid.insertAdjacentHTML('beforeend',`<div class="panel" id="cloudUsersPanel"><div class="panel-head"><h2>Benutzer & Rechte</h2>${cloud.user.role==='admin'?'<button class="btn small primary" onclick="openCloudUserDialog()">+ Benutzer</button>':''}</div><p class="muted">Angemeldet als <strong>${esc(cloud.user.name)}</strong> · ${esc(roleLabel[cloud.user.role]||cloud.user.role)}.</p><div id="cloudUserList">${canManage?'Benutzer werden geladen …':'Dein Zugang ist aktiv.'}</div></div>`);if(canManage)loadCloudUsers()}
async function loadCloudUsers(){const res=await fetch('/api/users');if(!res.ok)return;const data=await res.json();const wrap=document.getElementById('cloudUserList');if(!wrap)return;wrap.innerHTML=(data.users||[]).map(u=>`<div class="cloud-user-row"><div><b>${esc(u.name)}</b><div class="muted">${esc(u.email)} · ${esc(roleLabel[u.role]||u.role)}</div></div><span class="badge ${u.active?'green':'red'}">${u.active?'Aktiv':'Inaktiv'}</span></div>`).join('')}
function openCloudUserDialog(){const name=prompt('Name des neuen Benutzers:');if(!name)return;const email=prompt('E-Mail-Adresse:');if(!email)return;const password=prompt('Startpasswort (mindestens 10 Zeichen):');if(!password)return;const input=(prompt('Rolle: admin, manager, staff, cleaning oder viewer','staff')||'staff').toLowerCase();createCloudUser({name,email,password,role:input})}
async function createCloudUser(payload){const res=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)return alert(data.error||'Benutzer konnte nicht angelegt werden.');toast('Benutzer angelegt');loadCloudUsers()}
setTimeout(cloudBoot,0);

function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function closeModal(id){document.getElementById(id).classList.remove('show')}
function showModal(id){document.getElementById(id).classList.add('show')}
function showFormError(id,msg){const e=document.getElementById(id);e.textContent=msg;e.style.display='block'}
function hideFormError(id){document.getElementById(id).style.display='none'}
function toggleMenu(){document.getElementById('sidebar').classList.toggle('mobile-open')}
function goPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-'+page).classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.getElementById('pageTitle').textContent=pageMeta[page][0];document.getElementById('pageSubtitle').textContent=pageMeta[page][1];document.getElementById('sidebar').classList.remove('mobile-open');renderPage(page);window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>goPage(b.dataset.page)));
function overlaps(aFrom,aTo,bFrom,bTo){return aFrom<=bTo&&aTo>=bFrom}
function bookingConflict(roomId,from,to,ignoreId=''){return bookings.some(b=>b.id!==ignoreId&&b.status!=='cancelled'&&b.roomId===roomId&&overlaps(from,to,b.from,b.to))}
function bookedOn(roomId,date){return bookings.some(b=>b.status!=='cancelled'&&b.roomId===roomId&&b.from<=date&&b.to>=date)}
function bookingState(b){const t=todayIso();if(b.status==='cancelled')return ['Storniert','red'];if(b.status==='option')return ['Option','yellow'];if(b.to<t)return ['Abgeschlossen','green'];if(b.from>t)return ['Kommend','blue'];return ['Aktiv','orange']}
function roomName(id){return rooms.find(r=>r.id===id)?.name||'Unbekannter Raum'}
function renderAll(){persist();renderDashboard();renderCalendar();renderBookingTable();renderRoomsPage();renderGuestsPage();renderCleaning();renderTasks();fillSelectors();renderSettings()}
function renderPage(page){if(page==='dashboard')renderDashboard();if(page==='calendar'){renderCalendar();renderBookingTable()}if(page==='rooms')renderRoomsPage();if(page==='guests')renderGuestsPage();if(page==='cleaning')renderCleaning();if(page==='tasks')renderTasks();if(page==='documents')fillDocumentPicker();if(page==='settings'){renderSettings();renderCloudAccountPanel()}}
function renderDashboard(){const t=todayIso();const occupied=rooms.filter(r=>bookedOn(r.id,t)).length;const arrivals=bookings.filter(b=>b.status!=='cancelled'&&b.from===t).length;const openTasks=tasks.filter(x=>!x.done).length+rooms.filter(r=>r.cleaning!=='done').length;document.getElementById('statRooms').textContent=rooms.length;document.getElementById('statOccupied').textContent=occupied;document.getElementById('statOccupiedSub').textContent=`von ${rooms.length} Räumen`;document.getElementById('statArrivals').textContent=arrivals;document.getElementById('statTasks').textContent=openTasks;
const upcoming=[...bookings].filter(b=>b.status!=='cancelled'&&b.to>=t).sort((a,b)=>a.from.localeCompare(b.from)).slice(0,6);document.getElementById('dashboardBookings').innerHTML=upcoming.length?upcoming.map(b=>`<div class="row"><div class="row-main"><div class="row-title">${esc(b.guest)}</div><div class="row-meta">${esc(roomName(b.roomId))} · ${fmtDate(b.from)} – ${fmtDate(b.to)}${b.purpose?' · '+esc(b.purpose):''}</div></div><span class="badge ${bookingState(b)[1]}">${bookingState(b)[0]}</span></div>`).join(''):'<div class="empty">Keine kommenden Buchungen. Über „Neue Buchung“ geht es sofort los.</div>';
const clean=rooms.filter(r=>r.cleaning!=='done').slice(0,5);document.getElementById('dashboardCleaning').innerHTML=clean.length?clean.map(r=>`<div class="row"><div><div class="row-title">${esc(r.name)}</div><div class="row-meta">${esc(r.type)}</div></div><span class="badge ${r.cleaning==='doing'?'yellow':'red'}">${r.cleaning==='doing'?'In Reinigung':'Offen'}</span></div>`).join(''):'<div class="empty">Alles sauber ✓</div>';
const open=tasks.filter(x=>!x.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,5);document.getElementById('dashboardTasks').innerHTML=open.length?open.map(tk=>`<div class="row"><div><div class="row-title">${esc(tk.title)}</div><div class="row-meta">${tk.due?'Fällig '+fmtDate(tk.due):'Ohne Termin'}${tk.owner?' · '+esc(tk.owner):''}</div></div><span class="badge blue">Offen</span></div>`).join(''):'<div class="empty">Keine offenen Aufgaben ✓</div>'}
function renderCalendar(){const grid=document.getElementById('calendarGrid');if(!grid)return;const y=currentMonth.getFullYear(),m=currentMonth.getMonth();document.getElementById('calendarLabel').textContent=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(currentMonth);const weekdays=['Mo','Di','Mi','Do','Fr','Sa','So'];let html=weekdays.map(w=>`<div class="weekday">${w}</div>`).join('');const first=new Date(y,m,1);const offset=(first.getDay()+6)%7;const start=new Date(y,m,1-offset);for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=localIso(d),other=d.getMonth()!==m,isToday=iso===todayIso();const ev=bookings.filter(b=>b.status!=='cancelled'&&b.from<=iso&&b.to>=iso).slice(0,3);const count=bookings.filter(b=>b.status!=='cancelled'&&b.from<=iso&&b.to>=iso).length;html+=`<div class="day ${other?'other':''} ${isToday?'today':''}" ondblclick="openBookingModal(null,'${iso}')"><div class="day-num">${d.getDate()}</div>${ev.map(b=>`<div class="cal-event" title="${esc(b.guest)} – ${esc(roomName(b.roomId))}" onclick="editBooking('${b.id}');event.stopPropagation()">${esc(roomName(b.roomId))} · ${esc(b.guest)}</div>`).join('')}${count>3?`<div class="cal-more">+ ${count-3} weitere</div>`:''}</div>`}grid.innerHTML=html}
function changeMonth(delta){currentMonth.setMonth(currentMonth.getMonth()+delta);renderCalendar()}
function scrollToBookingList(){document.getElementById('bookingListPanel').scrollIntoView({behavior:'smooth'})}
function renderBookingTable(){const body=document.getElementById('bookingTable');if(!body)return;const q=(document.getElementById('bookingSearch')?.value||'').toLowerCase();const list=[...bookings].filter(b=>[b.guest,roomName(b.roomId),b.purpose,b.from,b.to].join(' ').toLowerCase().includes(q)).sort((a,b)=>b.from.localeCompare(a.from));body.innerHTML=list.length?list.map(b=>{const st=bookingState(b);return `<tr><td>${fmtDate(b.from)} – ${fmtDate(b.to)}</td><td><strong>${esc(b.guest)}</strong></td><td>${esc(roomName(b.roomId))}</td><td>${esc(b.purpose||'–')}</td><td><span class="badge ${st[1]}">${st[0]}</span></td><td><div class="row-actions"><button class="btn small" onclick="editBooking('${b.id}')">Bearbeiten</button><button class="btn small danger" onclick="deleteBooking('${b.id}')">Löschen</button></div></td></tr>`}).join(''):'<tr><td colspan="6"><div class="empty">Keine Buchungen gefunden.</div></td></tr>'}
function fillSelectors(){const opts=rooms.map(r=>`<option value="${r.id}">${esc(r.name)} · ${esc(r.type)}</option>`).join('');document.getElementById('bookingRoom').innerHTML=opts;document.getElementById('taskRoom').innerHTML='<option value="">Kein Raum</option>'+opts;document.getElementById('guestNames').innerHTML=guests.map(g=>`<option value="${esc(g.name)}"></option>`).join('');fillDocumentPicker()}
function openBookingModal(id=null,date=null){hideFormError('bookingError');document.getElementById('bookingId').value='';document.getElementById('bookingModalTitle').textContent='Neue Buchung';document.getElementById('bookingGuest').value='';document.getElementById('bookingPurpose').value='';document.getElementById('bookingParticipants').value='';document.getElementById('bookingNote').value='';document.getElementById('bookingStatus').value='confirmed';document.getElementById('bookingFrom').value=date||todayIso();document.getElementById('bookingTo').value=date||todayIso();fillSelectors();if(id)editBooking(id,true);else showModal('bookingModal')}
function editBooking(id,alreadyOpen=false){const b=bookings.find(x=>x.id===id);if(!b)return;hideFormError('bookingError');document.getElementById('bookingId').value=b.id;document.getElementById('bookingModalTitle').textContent='Buchung bearbeiten';document.getElementById('bookingGuest').value=b.guest;document.getElementById('bookingRoom').value=b.roomId;document.getElementById('bookingFrom').value=b.from;document.getElementById('bookingTo').value=b.to;document.getElementById('bookingPurpose').value=b.purpose||'';document.getElementById('bookingParticipants').value=b.participants||'';document.getElementById('bookingStatus').value=b.status||'confirmed';document.getElementById('bookingNote').value=b.note||'';if(!alreadyOpen)showModal('bookingModal')}
function saveBooking(){hideFormError('bookingError');const id=document.getElementById('bookingId').value;const roomId=document.getElementById('bookingRoom').value;const guest=document.getElementById('bookingGuest').value.trim();const from=document.getElementById('bookingFrom').value,to=document.getElementById('bookingTo').value;const status=document.getElementById('bookingStatus').value;if(!guest||!roomId||!from||!to)return showFormError('bookingError','Bitte Gast/Kunde, Raum und Zeitraum vollständig angeben.');if(to<from)return showFormError('bookingError','Das Bis-Datum darf nicht vor dem Von-Datum liegen.');if(status!=='cancelled'&&bookingConflict(roomId,from,to,id))return showFormError('bookingError',`${roomName(roomId)} ist in diesem Zeitraum bereits belegt.`);const data={id:id||uid(),roomId,guest,from,to,purpose:document.getElementById('bookingPurpose').value.trim(),participants:Number(document.getElementById('bookingParticipants').value)||null,status,note:document.getElementById('bookingNote').value.trim(),createdAt:id?(bookings.find(b=>b.id===id)?.createdAt||new Date().toISOString()):new Date().toISOString()};if(id)bookings=bookings.map(b=>b.id===id?data:b);else bookings.push(data);ensureGuestFromBooking(guest);persist();closeModal('bookingModal');renderAll();toast(id?'Buchung geändert':'Buchung gespeichert')}
function deleteBooking(id){const b=bookings.find(x=>x.id===id);if(!b||!confirm(`Buchung von ${b.guest} wirklich löschen?`))return;bookings=bookings.filter(x=>x.id!==id);persist();renderAll();toast('Buchung gelöscht')}
function ensureGuestFromBooking(name){if(!guests.some(g=>g.name.toLowerCase()===name.toLowerCase()))guests.push({id:uid(),name,email:'',phone:'',note:''})}
