function renderRoomsPage(){const wrap=document.getElementById('roomsGrid');if(!wrap)return;const q=(document.getElementById('roomSearch')?.value||'').toLowerCase();const t=todayIso();const list=rooms.filter(r=>[r.name,r.type,r.note].join(' ').toLowerCase().includes(q));wrap.innerHTML=list.length?list.map(r=>{const busy=bookedOn(r.id,t);return `<div class="room-card"><div class="room-top"><div><h3>${esc(r.name)}</h3><div class="muted">${esc(r.type)}</div></div><span class="badge ${busy?'orange':'green'}">${busy?'Heute belegt':'Heute frei'}</span></div><div class="room-info"><span>👥 ${r.capacity||1}</span><span>🧹 ${r.cleaning==='done'?'Sauber':r.cleaning==='doing'?'In Reinigung':'Offen'}</span></div><div class="row-meta">${esc(r.note||'Keine Ausstattung hinterlegt')}</div><div class="room-actions"><button class="btn small" onclick="openBookingModalForRoom('${r.id}')">Buchen</button><button class="btn small" onclick="editRoom('${r.id}')">Bearbeiten</button><button class="btn small danger" onclick="deleteRoom('${r.id}')">Löschen</button></div></div>`}).join(''):'<div class="empty">Keine Räume gefunden.</div>'}
function openBookingModalForRoom(id){openBookingModal();document.getElementById('bookingRoom').value=id}
function openRoomModal(){hideFormError('roomError');document.getElementById('roomId').value='';document.getElementById('roomModalTitle').textContent='Raum / Zimmer anlegen';document.getElementById('roomName').value='';document.getElementById('roomType').value='Einzelzimmer';document.getElementById('roomCapacity').value='1';document.getElementById('roomNote').value='';showModal('roomModal')}
function editRoom(id){const r=rooms.find(x=>x.id===id);if(!r)return;hideFormError('roomError');document.getElementById('roomId').value=r.id;document.getElementById('roomModalTitle').textContent='Raum / Zimmer bearbeiten';document.getElementById('roomName').value=r.name;document.getElementById('roomType').value=r.type;document.getElementById('roomCapacity').value=r.capacity||1;document.getElementById('roomNote').value=r.note||'';showModal('roomModal')}
function saveRoom(){hideFormError('roomError');const id=document.getElementById('roomId').value,name=document.getElementById('roomName').value.trim();if(!name)return showFormError('roomError','Bitte einen Namen eingeben.');const data={id:id||uid(),name,type:document.getElementById('roomType').value,capacity:Number(document.getElementById('roomCapacity').value)||1,note:document.getElementById('roomNote').value.trim(),cleaning:id?(rooms.find(r=>r.id===id)?.cleaning||'done'):'done'};rooms=id?rooms.map(r=>r.id===id?data:r):[...rooms,data];persist();closeModal('roomModal');renderAll();toast(id?'Raum geändert':'Raum angelegt')}
function deleteRoom(id){const r=rooms.find(x=>x.id===id);if(bookings.some(b=>b.roomId===id))return alert('Dieser Raum hat Buchungen und kann deshalb nicht gelöscht werden.');if(!confirm(`${r.name} wirklich löschen?`))return;rooms=rooms.filter(x=>x.id!==id);persist();renderAll();toast('Raum gelöscht')}
function renderGuestsPage(){const body=document.getElementById('guestTable');if(!body)return;const q=(document.getElementById('guestSearch')?.value||'').toLowerCase();const list=guests.filter(g=>[g.name,g.email,g.phone].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));body.innerHTML=list.length?list.map(g=>{const gb=bookings.filter(b=>b.guest.toLowerCase()===g.name.toLowerCase()).sort((a,b)=>b.from.localeCompare(a.from));const ref=gb[0];return `<tr><td><strong>${esc(g.name)}</strong>${g.note?`<div class="row-meta">${esc(g.note)}</div>`:''}</td><td>${esc(g.email||'–')}<div class="row-meta">${esc(g.phone||'')}</div></td><td>${gb.length}</td><td>${ref?fmtDate(ref.from)+' · '+esc(roomName(ref.roomId)):'–'}</td><td><div class="row-actions"><button class="btn small" onclick="editGuest('${g.id}')">Bearbeiten</button><button class="btn small" onclick="newBookingForGuest('${g.id}')">Buchen</button></div></td></tr>`}).join(''):'<tr><td colspan="5"><div class="empty">Noch keine Gäste/Kunden angelegt. Neue Buchungen legen Kontakte automatisch an.</div></td></tr>'}
function openGuestModal(){hideFormError('guestError');document.getElementById('guestId').value='';document.getElementById('guestModalTitle').textContent='Gast / Kunde anlegen';['guestName','guestEmail','guestPhone','guestNote'].forEach(id=>document.getElementById(id).value='');showModal('guestModal')}
function editGuest(id){const g=guests.find(x=>x.id===id);if(!g)return;hideFormError('guestError');document.getElementById('guestId').value=g.id;document.getElementById('guestModalTitle').textContent='Gast / Kunde bearbeiten';document.getElementById('guestName').value=g.name;document.getElementById('guestEmail').value=g.email||'';document.getElementById('guestPhone').value=g.phone||'';document.getElementById('guestNote').value=g.note||'';showModal('guestModal')}
function saveGuest(){hideFormError('guestError');const id=document.getElementById('guestId').value,name=document.getElementById('guestName').value.trim();if(!name)return showFormError('guestError','Bitte einen Namen eingeben.');const old=id?guests.find(g=>g.id===id):null;const data={id:id||uid(),name,email:document.getElementById('guestEmail').value.trim(),phone:document.getElementById('guestPhone').value.trim(),note:document.getElementById('guestNote').value.trim()};if(old&&old.name!==name)bookings=bookings.map(b=>b.guest===old.name?{...b,guest:name}:b);guests=id?guests.map(g=>g.id===id?data:g):[...guests,data];persist();closeModal('guestModal');renderAll();toast(id?'Kontakt geändert':'Kontakt angelegt')}
function newBookingForGuest(id){const g=guests.find(x=>x.id===id);openBookingModal();document.getElementById('bookingGuest').value=g?.name||''}
function renderCleaning(){const list=document.getElementById('cleaningList');if(!list)return;const open=rooms.filter(r=>r.cleaning==='open').length,doing=rooms.filter(r=>r.cleaning==='doing').length,done=rooms.filter(r=>r.cleaning==='done').length,pct=rooms.length?Math.round(done/rooms.length*100):100;document.getElementById('cleanOpen').textContent=open;document.getElementById('cleanDoing').textContent=doing;document.getElementById('cleanDone').textContent=done;document.getElementById('cleanPercent').textContent=pct+'%';list.innerHTML=rooms.map(r=>`<div class="clean-card"><div><div class="row-title">${esc(r.name)}</div><div class="row-meta">${esc(r.type)}${nextBookingText(r.id)}</div></div><div class="row-actions"><button class="btn small ${r.cleaning==='open'?'danger':''}" onclick="setCleaning('${r.id}','open')">Offen</button><button class="btn small" onclick="setCleaning('${r.id}','doing')">In Reinigung</button><button class="btn small" onclick="setCleaning('${r.id}','done')">Sauber ✓</button></div></div>`).join('')}
function nextBookingText(roomId){const t=todayIso();const b=bookings.filter(b=>b.roomId===roomId&&b.status!=='cancelled'&&b.from>=t).sort((a,b)=>a.from.localeCompare(b.from))[0];return b?` · nächste Belegung ${fmtDate(b.from)}`:''}
function setCleaning(id,status){rooms=rooms.map(r=>r.id===id?{...r,cleaning:status}:r);persist();renderCleaning();renderDashboard();renderRoomsPage();toast('Reinigungsstatus geändert')}
function setTaskFilter(f,el){taskFilter=f;document.querySelectorAll('[data-task-filter]').forEach(b=>b.classList.remove('active'));el.classList.add('active');renderTasks()}
function renderTasks(){const wrap=document.getElementById('taskList');if(!wrap)return;let list=[...tasks];if(taskFilter==='open')list=list.filter(t=>!t.done);if(taskFilter==='done')list=list.filter(t=>t.done);list.sort((a,b)=>(a.done-b.done)||((a.due||'9999').localeCompare(b.due||'9999')));wrap.innerHTML=list.length?list.map(t=>`<div class="task-card"><div><div class="row-title" style="${t.done?'text-decoration:line-through;color:#8a93a4':''}">${esc(t.title)}</div><div class="row-meta">${t.due?'Fällig '+fmtDate(t.due):'Ohne Termin'}${t.owner?' · '+esc(t.owner):''}${t.roomId?' · '+esc(roomName(t.roomId)):''}</div></div><div class="row-actions"><button class="btn small" onclick="toggleTask('${t.id}')">${t.done?'Wieder öffnen':'Erledigt ✓'}</button><button class="btn small danger" onclick="deleteTask('${t.id}')">Löschen</button></div></div>`).join(''):'<div class="empty">Hier ist alles erledigt.</div>'}
function openTaskModal(){hideFormError('taskError');document.getElementById('taskTitle').value='';document.getElementById('taskDue').value=todayIso();document.getElementById('taskOwner').value='';fillSelectors();document.getElementById('taskRoom').value='';showModal('taskModal')}
function saveTask(){hideFormError('taskError');const title=document.getElementById('taskTitle').value.trim();if(!title)return showFormError('taskError','Bitte eine Aufgabe eingeben.');tasks.push({id:uid(),title,due:document.getElementById('taskDue').value,owner:document.getElementById('taskOwner').value.trim(),roomId:document.getElementById('taskRoom').value,done:false});persist();closeModal('taskModal');renderAll();toast('Aufgabe angelegt')}
function toggleTask(id){tasks=tasks.map(t=>t.id===id?{...t,done:!t.done}:t);persist();renderTasks();renderDashboard()}
function deleteTask(id){tasks=tasks.filter(t=>t.id!==id);persist();renderTasks();renderDashboard();toast('Aufgabe gelöscht')}
function fillDocumentPicker(){const s=document.getElementById('documentBooking');if(!s)return;const list=[...bookings].filter(b=>b.status!=='cancelled').sort((a,b)=>b.from.localeCompare(a.from));s.innerHTML=list.length?list.map(b=>`<option value="${b.id}">${fmtDate(b.from)} · ${esc(b.guest)} · ${esc(roomName(b.roomId))}</option>`).join(''):'<option value="">Keine Buchung vorhanden</option>'}
function openDocumentPicker(){fillDocumentPicker();showModal('documentModal')}
function createConfirmation(){const id=document.getElementById('documentBooking').value,b=bookings.find(x=>x.id===id);if(!b)return alert('Bitte zuerst eine Buchung anlegen.');const r=rooms.find(x=>x.id===b.roomId);const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><title>Buchungsbestätigung</title><style>body{font-family:Arial;max-width:760px;margin:50px auto;color:#172033;line-height:1.5}h1{margin-bottom:4px}.box{border:1px solid #ddd;border-radius:12px;padding:20px;margin:24px 0}.row{display:grid;grid-template-columns:180px 1fr;padding:7px 0;border-bottom:1px solid #eee}.row:last-child{border:0}.muted{color:#666}@media print{button{display:none}}</style></head><body><h1>${esc(settings.org||'Raum- & Zimmerverwaltung')}</h1><div class="muted">Buchungsbestätigung</div><div class="box"><div class="row"><b>Gast / Kunde</b><span>${esc(b.guest)}</span></div><div class="row"><b>Raum / Zimmer</b><span>${esc(r?.name||'')}</span></div><div class="row"><b>Zeitraum</b><span>${fmtDate(b.from)} – ${fmtDate(b.to)}</span></div><div class="row"><b>Zweck</b><span>${esc(b.purpose||'–')}</span></div><div class="row"><b>Teilnehmer</b><span>${b.participants||'–'}</span></div><div class="row"><b>Notiz</b><span>${esc(b.note||'–')}</span></div></div><p>${esc(settings.address||'')}</p><p>${esc(settings.email||'')} ${settings.phone?'· '+esc(settings.phone):''}</p><button onclick="window.print()">Drucken / als PDF speichern</button></body></html>`);w.document.close();closeModal('documentModal')}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function exportBookingsCsv(){const rows=[['Von','Bis','Gast/Kunde','Raum','Zweck','Teilnehmer','Status'],...bookings.map(b=>[b.from,b.to,b.guest,roomName(b.roomId),b.purpose||'',b.participants||'',b.status])];downloadFile('buchungen.csv','\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\n'),'text/csv;charset=utf-8');toast('CSV exportiert')}
function exportData(){downloadFile('raumwerk-sicherung-'+todayIso()+'.json',JSON.stringify({version:1,rooms,bookings,guests,tasks,settings},null,2),'application/json');toast('Datensicherung erstellt')}
function downloadFile(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(e){const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(rd.result);if(!Array.isArray(d.rooms)||!Array.isArray(d.bookings))throw new Error();rooms=d.rooms;bookings=d.bookings;guests=d.guests||[];tasks=d.tasks||[];settings=d.settings||settings;persist();renderAll();toast('Datensicherung eingelesen')}catch{alert('Die Datei konnte nicht eingelesen werden.')}};rd.readAsText(f);e.target.value=''}
function renderSettings(){document.getElementById('settingOrg').value=settings.org||'';document.getElementById('settingEmail').value=settings.email||'';document.getElementById('settingPhone').value=settings.phone||'';document.getElementById('settingAddress').value=settings.address||''}
function saveSettings(){settings={org:document.getElementById('settingOrg').value.trim(),email:document.getElementById('settingEmail').value.trim(),phone:document.getElementById('settingPhone').value.trim(),address:document.getElementById('settingAddress').value.trim()};persist();toast('Einstellungen gespeichert')}
function loadDemoData(){const t=new Date(),plus=n=>{const d=new Date(t);d.setDate(d.getDate()+n);return localIso(d)};if(!bookings.length)bookings=[{id:uid(),roomId:'r1',guest:'Jugendwerk Beispiel',from:plus(0),to:plus(0),purpose:'Workshop',participants:18,status:'confirmed',note:'',createdAt:new Date().toISOString()},{id:uid(),roomId:'r6',guest:'Maria Schneider',from:plus(0),to:plus(2),purpose:'Übernachtung',participants:1,status:'confirmed',note:'Anreise ab 15 Uhr',createdAt:new Date().toISOString()},{id:uid(),roomId:'r2',guest:'Kirchengemeinderat',from:plus(3),to:plus(3),purpose:'Sitzung',participants:14,status:'option',note:'',createdAt:new Date().toISOString()}];if(!guests.length)guests=[{id:uid(),name:'Jugendwerk Beispiel',email:'kontakt@beispiel.de',phone:'',note:''},{id:uid(),name:'Maria Schneider',email:'maria@beispiel.de',phone:'0711 123456',note:''},{id:uid(),name:'Kirchengemeinderat',email:'',phone:'',note:''}];if(!tasks.length)tasks=[{id:uid(),title:'Schlüssel für Gästezimmer 203 vorbereiten',due:plus(0),owner:'Empfang',roomId:'r6',done:false},{id:uid(),title:'Bestuhlung Seminarraum Luther prüfen',due:plus(0),owner:'Hausdienst',roomId:'r1',done:false}];persist();renderAll();toast('Demo-Daten geladen')}
function resetAllData(){if(!confirm('Wirklich alle lokalen Daten dieser V1 löschen?'))return;['raumwerk_rooms_v2','raumwerk_bookings','raumwerk_guests','raumwerk_tasks','raumwerk_settings'].forEach(k=>localStorage.removeItem(k));rooms=JSON.parse(JSON.stringify(defaultRooms));bookings=[];guests=[];tasks=[];settings={org:'Evangelische Einrichtung',email:'',phone:'',address:''};renderAll();toast('Daten zurückgesetzt')}
function init(){document.getElementById('pageSubtitle').textContent=pageMeta.dashboard[1];fillSelectors();renderAll();}
init();