let publicRooms=[];let selectedRoom='';let currentAvailable=[];let bookingMode='request';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
document.getElementById('from').value=today();document.getElementById('to').value=today();
boot();
async function boot(){try{const r=await fetch('/api/public/config');const d=await r.json();if(!r.ok)throw new Error(d.error||'Online-Buchung ist noch nicht aktiv.');document.getElementById('orgName').textContent=d.organization||'Online-Buchung';publicRooms=d.rooms||[];bookingMode=d.mode==='direct'?'direct':'request';applyBookingMode();renderRooms([])}catch(e){showError(e.message);document.getElementById('availabilityNote').textContent='Die Online-Buchung ist noch nicht mit dem zentralen Backend verbunden.'}}
function applyBookingMode(){const direct=bookingMode==='direct';const title=document.getElementById('heroTitle'),text=document.getElementById('heroText'),button=document.getElementById('submitBooking');if(title)title.textContent=direct?'Raum oder Zimmer direkt buchen':'Raum oder Zimmer anfragen';if(text)text.textContent=direct?'Zeitraum auswählen, freien Raum wählen und direkt verbindlich buchen. Die Verfügbarkeit wird beim Absenden erneut geprüft.':'Zeitraum auswählen, freien Raum wählen und Anfrage senden. Die Einrichtung bestätigt anschließend die Buchung.';if(button)button.textContent=direct?'Jetzt verbindlich buchen':'Buchungsanfrage senden'}
async function checkAvailability(){hideMessages();const from=document.getElementById('from').value,to=document.getElementById('to').value;if(!from||!to||to<from)return showError('Bitte einen gültigen Zeitraum auswählen.');try{const r=await fetch('/api/public/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from,to})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Verfügbarkeit konnte nicht geprüft werden.');selectedRoom='';currentAvailable=d.rooms||[];renderRooms(currentAvailable);const n=currentAvailable.length;document.getElementById('availabilityNote').textContent=n?`${n} Raum/Räume sind verfügbar. Bitte auswählen.`:'In diesem Zeitraum ist aktuell kein Raum verfügbar.'}catch(e){showError(e.message)}}
function renderRooms(available){const checked=new Set(available);document.getElementById('rooms').innerHTML=publicRooms.map(r=>`<div class="room ${available.length&&!checked.has(r.id)?'off':''} ${selectedRoom===r.id?'active':''}" onclick="selectRoom('${safe(r.id)}')"><h3>${safe(r.name)}</h3><div class="muted">${safe(r.type)} · bis ${Number(r.capacity)||1} Pers.</div>${r.note?`<div class="muted" style="margin-top:6px">${safe(r.note)}</div>`:''}</div>`).join('')}
function selectRoom(id){if(currentAvailable.length&&!currentAvailable.includes(id))return;selectedRoom=id;renderRooms(currentAvailable);document.getElementById('availabilityNote').textContent=`Ausgewählt: ${publicRooms.find(r=>r.id===id)?.name||''}`}
async function sendRequest(){hideMessages();const payload={name:v('name'),email:v('email'),phone:v('phone'),purpose:v('purpose'),participants:Number(v('participants'))||1,note:v('note'),website:v('website'),roomId:selectedRoom,from:v('from'),to:v('to')};if(!payload.roomId)return showError('Bitte zuerst einen verfügbaren Raum auswählen.');if(!payload.name||!payload.email)return showError('Bitte Name und E-Mail ausfüllen.');const room=publicRooms.find(r=>r.id===payload.roomId);if(room&&payload.participants>Number(room.capacity||1))return showError(`Dieser Raum ist für maximal ${Number(room.capacity)||1} Personen ausgelegt.`);try{const r=await fetch('/api/public/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||(bookingMode==='direct'?'Buchung konnte nicht abgeschlossen werden.':'Anfrage konnte nicht gesendet werden.'));document.getElementById('success').style.display='block';document.getElementById('success').textContent=d.message||(d.mode==='direct'?'Die Buchung wurde verbindlich bestätigt.':'Danke! Die Buchungsanfrage wurde an die Einrichtung übermittelt.');['name','email','phone','purpose','note'].forEach(id=>document.getElementById(id).value='');selectedRoom='';await checkAvailability()}catch(e){showError(e.message)}}
function v(id){return document.getElementById(id).value.trim()}
function showError(msg){const e=document.getElementById('error');e.textContent=msg;e.style.display='block'}
function hideMessages(){document.getElementById('error').style.display='none';document.getElementById('success').style.display='none'}
function safe(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}